import { HallmarkingTopic } from '../types/index.ts';

export const HALLMARKING_DATA: HallmarkingTopic[] = [
  {
    id: 'huid-system',
    title: 'Hallmark Unique Identification (HUID) System',
    category: 'HUID',
    summary: 'HUID is a 6-digit alphanumeric code laser engraved on every single piece of hallmarked gold jewellery. Each piece of jewellery receives a completely unique number that provides end-to-end traceability.',
    details: [
      'HUID stands for Hallmark Unique Identification. It was introduced by the Central Government and BIS to eliminate duplication, fraud, and adulteration in the gold jewellery supply chain.',
      'The 6-character alphanumeric code (e.g. AB1234, 7K9Y2M) is generated by a central secure BIS server when the jewellery is submitted to an Assaying and Hallmarking Centre (AHC).',
      'The AHC assays the metal purity (using fire assay per IS 1418) and micro-laser inscribes the HUID directly onto the jewellery alongside the BIS logo and purity grade.',
      'No two pieces of jewellery in the country can possess the identical HUID code.'
    ],
    official_steps: [
      'Jeweller registers with BIS on Manakonline portal.',
      'Jeweller deposits jewellery batch at a BIS-recognized Assaying and Hallmarking Centre (AHC).',
      'AHC tests sample purity through XRF and fire assay.',
      'Central BIS server allocates unique 6-digit HUID upon passing purity test.',
      'AHC laser engraves the 3 marks onto the jewellery and returns it to the jeweller.'
    ],
    source_url: 'https://www.bis.gov.in/hallmarking-overview'
  },
  {
    id: 'hallmark-marks',
    title: 'The 3 Mandatory Marks on Gold Jewellery',
    category: 'MARKS',
    summary: 'As per revised BIS hallmarking norms, hallmarked gold jewellery carries exactly 3 distinct marks. Consumers must inspect all 3 marks before purchasing.',
    details: [
      '1. BIS Standard Mark: The official triangular logo of the Bureau of Indian Standards indicating conformity to Indian Standard IS 1417.',
      '2. Purity / Fineness Mark: Denotes Karat and parts per thousand purity: 24K (995), 23K (958), 22K (916 - most popular), 20K (833), 18K (750), 14K (585). For example, "22K916" indicates 22 Karat gold with 91.6% pure gold content.',
      '3. 6-Digit Alphanumeric HUID: Unique 6-character laser mark (e.g. 9F3B8Q) enabling digital consumer verification.',
      'Note: Prior marks like jeweller identification logo and AHC logo have been superseded by the centralized HUID code to prevent counterfeiting.'
    ],
    source_url: 'https://www.bis.gov.in/hallmarking-overview'
  },
  {
    id: 'mandatory-districts',
    title: 'Mandatory Hallmarking Coverage & Phases',
    category: 'MANDATORY_DISTRICTS',
    summary: 'Hallmarking of gold jewellery has been made mandatory across 343+ districts in India in phased rollout, covering all districts where at least one AHC is operational.',
    details: [
      'Phase I (June 2021): Implemented in 256 districts across 28 States and Union Territories.',
      'Phase II (June 2022): Extended to 32 additional districts.',
      'Phase III & IV (2023-2024): Extended to over 343 districts covering major gold trading centers across all Indian states.',
      'In these mandatory districts, no registered jeweller is legally permitted to sell un-hallmarked gold jewellery of 14, 18, 20, 22, 23, or 24 Karats.',
      'Exemptions: Export consignments, jewellery weighing less than 2 grams, medical/scientific items, and gold bullion for industrial processing.'
    ],
    source_url: 'https://www.bis.gov.in/hallmarking-overview'
  },
  {
    id: 'consumer-verification',
    title: 'How Consumers Can Verify Hallmarked Jewellery',
    category: 'CONSUMER_VERIFICATION',
    summary: 'Consumers can independently verify the authenticity of any gold jewellery using the free official "BIS Care App" on Android and iOS.',
    details: [
      'Step 1: Download the official "BIS Care App" from Google Play Store or Apple App Store.',
      'Step 2: Open the app and tap on the "Verify HUID" icon on the home dashboard.',
      'Step 3: Enter the 6-digit alphanumeric HUID engraved on your jewellery piece.',
      'Step 4: The app immediately returns: Jeweller BIS Registration Number, Jeweller Name and Address, Assaying & Hallmarking Centre (AHC) Name, Jewellery Article Type (e.g. Ring, Bangle, Necklace), Purity Karat/Fineness (e.g. 22K916), and Date of Hallmarking.',
      'If the HUID does not exist or details do not match the physical piece or bill, the consumer can instantly lodge a complaint through the app.'
    ],
    official_steps: [
      'Locate the 6-digit laser engraved code using a magnifying loupe at the jewellery showroom.',
      'Input the code in the "Verify HUID" tool of BIS Care App.',
      'Cross-check that the description and purity match your invoice description.'
    ],
    source_url: 'https://services.bis.gov.in'
  },
  {
    id: 'ahc-locator',
    title: 'Finding Licensed Assaying & Hallmarking Centres (AHC)',
    category: 'AHC_CENTRES',
    summary: 'BIS operates a nationwide network of over 1,500+ recognized third-party Assaying & Hallmarking Centres (AHCs) and Off-site Collection Centres (OSCs).',
    details: [
      'AHCs are independent third-party laboratories recognized by BIS under IS 15820 for assaying precious metal jewellery.',
      'To locate authorized AHCs in your state or district: visit the official BIS portal at www.bis.gov.in -> Navigate to "Hallmarking" -> "Assaying and Hallmarking" -> "List of Recognized AHCs".',
      'The portal provides full searchability by State, District, and PIN Code.',
      'Consumers can also get their own personal un-hallmarked family jewellery tested for purity at any recognized AHC by paying the nominal official testing fee (Rs. 45/- per article for gold) and receiving an official assay report.'
    ],
    source_url: 'https://www.bis.gov.in'
  },
  {
    id: 'silver-hallmarking',
    title: 'Silver Jewellery & Artefacts Hallmarking',
    category: 'SILVER',
    summary: 'Hallmarking for silver jewellery and artefacts is currently voluntary under IS 2112:2014, offering assurance of purity to consumers.',
    details: [
      'Governed by Indian Standard IS 2112:2014.',
      'Recognized silver purity grades: 990 (99.0% Fine silver), 925 (92.5% Sterling silver - standard for silverware and jewellery), 900 (90.0%), 835 (83.5%), 800 (80.0%).',
      'Marks on hallmarked silver: (1) BIS Logo, (2) Purity grade (e.g. 925), (3) AHC identification mark, (4) Jeweller mark.',
      'Testing method is potentiometric titration in accordance with IS 2113.'
    ],
    source_url: 'https://www.bis.gov.in/hallmarking-overview'
  }
];
